services:
  - type: web
    name: oil-spill-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/app.py
    plan: free
    envVars:
      - key: PORT
        value: 7860